# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

server:
  port: 1111   # HTTP (Tomcat) port; Eureka default port 8761

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  application:
    name: hello-service
  thymeleaf:
    enabled: false     # Disable Thymeleaf